name: build

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        ######################################################## generate gradle secrets
      - uses: actions/checkout@v2
      - name: 🎨 create gradle.properties
        shell: bash
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
          RADIO_DB_URL: ${{ secrets.RADIO_DB_URL }}
          RADIO_DB_USER: ${{ secrets.RADIO_DB_USER }}
          RADIO_DB_PASSWORD: ${{ secrets.RADIO_DB_PASSWORD }}
        run: |
          mkdir -p ~/.gradle/
          echo "::set-env name=GRADLE_USER_HOME::$HOME/.gradle"
          echo "RADIO_DB_URL=$RADIO_DB_URL" >> ~/.gradle/gradle.properties
          echo "RADIO_DB_USER=$RADIO_DB_USER" >> ~/.gradle/gradle.properties
          echo "RADIO_DB_PASSWORD=$RADIO_DB_PASSWORD" >> ~/.gradle/gradle.properties



        ######################################################## setup jdk
      - name: 🖥️ Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'



        ######################################################## setup gradle
      - name: 🖥️ Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b



        ######################################################## build gradle
      - name: 🏛️ gradlew build
        run: |
          ./gradlew clean build



        ######################################################## release on github
      - name: 🎨 create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Radio: Latest!"
          files: |
            LICENSE
            build/libs/Radio-all.jar



        ######################################################## setup docker
      - name: 🖥️ Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
#


        ######################################################## login to dockerhub
      - name: 📜 Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}



        ######################################################## login to github registry
      - name: 📜 Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}



        ######################################################## build and push the image
      - name: 🏗️ Build and push
        uses: docker/build-push-action@master
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            toadsy/radio:latest
            ghcr.io/toadless/radio:latest



        ######################################################## reload my vps
      - name: 🔃 reload vps
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASS }}
          port: 22
          script: |
            cd ~/docker/radio
            ./rebuild
