name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: create gradle.properties
        uses: actions/checkout@v2
        shell: bash
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
          RADIO_DB_URL: ${{ secrets.RADIO_DB_URL }}
          RADIO_DB_USER: ${{ secrets.RADIO_DB_USER }}
          RADIO_DB_PASSWORD: ${{ secrets.RADIO_DB_PASSWORD }}
        run: |
          mkdir -p ~/.gradle/
          echo "::set-env name=GRADLE_USER_HOME::$HOME/.gradle"
          echo "RADIO_DB_URL=$RADIO_DB_URL" >> ~/.gradle/gradle.properties
          echo "RADIO_DB_USER=$RADIO_DB_USER" >> ~/.gradle/gradle.properties
          echo "RADIO_DB_PASSWORD=$RADIO_DB_PASSWORD" >> ~/.gradle/gradle.properties

      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: gradlew build
        run: |
          ./gradlew clean build

      - name: docker build
        run: |
          docker build . -t toadlesss/radio:latest

      - name: docker push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
          repository: toadlesss/radio
          tags: latest